# Generated by Django 5.0.6 on 2024-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_info',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
