# Generated by Django 5.1.4 on 2025-01-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court_info',
            fields=[
                ('Court_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Court_name', models.CharField(max_length=25)),
                ('Address', models.TextField(max_length=125)),
                ('level', models.CharField(max_length=25)),
                ('Phone_no', models.IntegerField(max_length=13)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
