# Generated by Django 5.0.6 on 2024-06-21 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
