# Generated by Django 5.1.4 on 2025-01-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0002_court_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court_info',
            old_name='level',
            new_name='Level',
        ),
    ]
