# Generated by Django 5.0.6 on 2024-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0002_alter_login_info_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
