# Generated by Django 5.1.4 on 2025-01-06 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0003_rename_level_court_info_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court_info',
            name='Phone_no',
        ),
        migrations.AddField(
            model_name='court_info',
            name='phone_no',
            field=models.CharField(default=123456789, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
