# Generated by Django 5.1.4 on 2025-01-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0004_remove_court_info_phone_no_court_info_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court_info',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
