# Generated by Django 5.1.4 on 2025-01-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0005_alter_court_info_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court_info',
            old_name='phone_no',
            new_name='Phone_no',
        ),
    ]
