# Generated by Django 5.1.4 on 2025-01-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0006_rename_phone_no_court_info_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge_info',
            fields=[
                ('Judge_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=25)),
                ('L_name', models.CharField(max_length=25)),
                ('Designation', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=250)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.court_info', verbose_name='Court Info')),
            ],
        ),
    ]
