# Generated by Django 5.1.4 on 2025-01-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0007_judge_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim_info',
            fields=[
                ('Victim_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=25)),
                ('L_name', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Nationality', models.CharField(max_length=25)),
                ('Address', models.TextField(max_length=250)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.court_info', verbose_name='cout info')),
                ('Judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.judge_info', verbose_name='judge info')),
            ],
        ),
    ]
