# Generated by Django 5.1.4 on 2025-01-09 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0008_victim_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offender_info',
            fields=[
                ('Offender_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=25)),
                ('L_name', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Nationality', models.CharField(max_length=25)),
                ('Address', models.TextField(max_length=250)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Offense_type', models.CharField(max_length=50)),
                ('Bail_status', models.CharField(max_length=50)),
                ('Jail_terms', models.CharField(max_length=50, null=True)),
                ('Court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.court_info', verbose_name='cout info')),
                ('Judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.judge_info', verbose_name='judge info')),
                ('Victim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.victim_info', verbose_name=' victim info')),
            ],
        ),
    ]
