# Generated by Django 5.1.4 on 2025-01-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0009_offender_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender_info',
            name='Jail_terms',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Crime_info',
            fields=[
                ('Crime_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('Crime_type', models.CharField(max_length=50)),
                ('Weapon_used', models.CharField(max_length=125)),
                ('Crime_date', models.CharField(max_length=25)),
                ('Crime_time', models.CharField(max_length=25)),
                ('Crime_loccation', models.CharField(max_length=125)),
                ('Offender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.offender_info', verbose_name='offender info')),
                ('Victim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.victim_info', verbose_name=' victim info')),
            ],
        ),
        migrations.CreateModel(
            name='Prison_information',
            fields=[
                ('Prison_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('Prison_name', models.CharField(max_length=125)),
                ('Telephone_no', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=250)),
                ('Offender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.offender_info', verbose_name='offender info')),
            ],
        ),
        migrations.CreateModel(
            name='Guard_information',
            fields=[
                ('Guard_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=25)),
                ('L_name', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField(max_length=250)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Shift_start', models.CharField(max_length=50)),
                ('Shift_end', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Prison_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_rec_app.prison_information', verbose_name='prison information')),
            ],
        ),
    ]
