# Generated by Django 5.1.4 on 2025-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0010_alter_offender_info_jail_terms_crime_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment_info',
            fields=[
                ('Punishment_id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('Frome_date', models.CharField(max_length=25)),
                ('From_time', models.CharField(max_length=25)),
                ('To_date', models.CharField(max_length=25)),
                ('To_time', models.CharField(max_length=25)),
                ('Total_duration', models.CharField(max_length=25)),
                ('Punishment_desc', models.TextField(max_length=500)),
                ('Punishment_inc', models.CharField(max_length=15)),
                ('Reason_punishment_inc', models.CharField(max_length=500)),
                ('Offender_id', models.CharField(max_length=25)),
                ('Prison_id', models.CharField(max_length=25)),
                ('Judge_id', models.CharField(max_length=25)),
            ],
        ),
    ]
