# Generated by Django 5.1.4 on 2025-01-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0011_punishment_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishment_info',
            old_name='Frome_date',
            new_name='From_date',
        ),
    ]
