# Generated by Django 5.1.4 on 2025-01-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_rec_app', '0012_rename_frome_date_punishment_info_from_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishment_info',
            old_name='Total_duration',
            new_name='Total_duration_days',
        ),
    ]
